name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build and Run the Docker image
      run: docker build . --file Dockerfile --tag tms/lesson58:latest && docker stop tms/lesson58:latest && docker run -d -p 8080:8080 tms/lesson58:latest
